# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1l3O8zzc7w8ZhOLGGKbIZ15fo7i15_o4l
"""

import streamlit as st
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression

# ---------------------------------
# Page Configuration
# ---------------------------------
st.set_page_config(
    page_title="Employee Retention Prediction",
    page_icon="👨‍💼",
    layout="wide"
)

# ---------------------------------
# Sidebar
# ---------------------------------
st.sidebar.title("👨‍💼 Employee Retention")

st.sidebar.markdown("""
### About

This application predicts whether an employee is likely to **stay** or **leave** the company using **Logistic Regression**.

**Dataset Used:** HR_comma_sep.csv

**Target Variable:** left
""")

# ---------------------------------
# Title
# ---------------------------------
st.title("👨‍💼 Employee Retention Prediction")

st.write("""
Analyze employee information and predict whether an employee is likely to **leave** or **stay** in the company.
""")

st.divider()

# ---------------------------------
# Load Dataset
# ---------------------------------
@st.cache_data
def load_data():
    return pd.read_csv("HR_comma_sep.csv")

df = load_data()

# ---------------------------------
# Dataset Preview
# ---------------------------------
st.header("📂 Dataset Preview")

with st.expander("Click to View Dataset"):
    st.dataframe(df)

st.write("**Dataset Shape:**", df.shape)

st.divider()

# ---------------------------------
# Employee Statistics
# ---------------------------------
left = df[df.left == 1]
retained = df[df.left == 0]

col1, col2, col3 = st.columns(3)

col1.metric("👨 Total Employees", len(df))
col2.metric("❌ Left", left.shape[0])
col3.metric("✅ Retained", retained.shape[0])

st.divider()

# ---------------------------------
# Average Values
# ---------------------------------
st.header("📊 Average Values")

average_values = df.groupby("left").mean(numeric_only=True)

st.dataframe(average_values)

with st.expander("📌 Key Observations"):

    st.markdown("""
- Employees with **low satisfaction levels** are more likely to leave.

- Employees working **higher monthly hours** are more likely to leave.

- Employees who received **promotions** are more likely to stay.

- Employees with **higher salaries** are more likely to stay.
""")

st.divider()

# ---------------------------------
# Charts
# ---------------------------------
col1, col2 = st.columns(2)

with col1:

    st.subheader("💰 Salary Impact")

    salary_chart = pd.crosstab(df["salary"], df["left"])

    st.bar_chart(salary_chart)

with col2:

    st.subheader("🏢 Department Impact")

    department_chart = pd.crosstab(df["Department"], df["left"])

    st.bar_chart(department_chart)

st.info("Department has only a minor impact on employee retention, so it is not used for model training.")

st.divider()

# ---------------------------------
# Feature Selection
# ---------------------------------
subdf = df[
    [
        "satisfaction_level",
        "average_montly_hours",
        "promotion_last_5years",
        "salary"
    ]
]

salary_dummies = pd.get_dummies(subdf["salary"], prefix="salary")

df_with_dummies = pd.concat([subdf, salary_dummies], axis=1)

df_with_dummies.drop("salary", axis=1, inplace=True)

X = df_with_dummies
y = df["left"]

# ---------------------------------
# Train Test Split
# ---------------------------------
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    train_size=0.30,
    random_state=42
)

# ---------------------------------
# Model Training
# ---------------------------------
model = LogisticRegression(max_iter=1000)

model.fit(X_train, y_train)

accuracy = model.score(X_test, y_test)

st.header("🎯 Model Performance")

st.metric(
    label="Model Accuracy",
    value=f"{accuracy*100:.2f}%"
)

st.divider()

# ---------------------------------
# Prediction
# ---------------------------------
st.header("📝 Predict Employee Retention")

with st.form("prediction_form"):

    satisfaction = st.slider(
        "Satisfaction Level",
        0.0,
        1.0,
        0.50
    )

    hours = st.slider(
        "Average Monthly Hours",
        80,
        320,
        200
    )

    promotion = st.selectbox(
        "Promotion in Last 5 Years",
        [0, 1]
    )

    salary = st.selectbox(
        "Salary Level",
        ["low", "medium", "high"]
    )

    submitted = st.form_submit_button("🔍 Predict")

salary_low = 0
salary_medium = 0
salary_high = 0

if salary == "low":
    salary_low = 1
elif salary == "medium":
    salary_medium = 1
else:
    salary_high = 1

if submitted:

    input_data = pd.DataFrame({
        "satisfaction_level": [satisfaction],
        "average_montly_hours": [hours],
        "promotion_last_5years": [promotion],
        "salary_high": [salary_high],
        "salary_low": [salary_low],
        "salary_medium": [salary_medium]
    })

    prediction = model.predict(input_data)

    probability = model.predict_proba(input_data)

    st.subheader("Prediction Result")

    if prediction[0] == 1:
        st.error("⚠️ The employee is likely to leave the company.")
    else:
        st.success("✅ The employee is likely to stay in the company.")

    stay = probability[0][0]
    leave = probability[0][1]

    st.write("### Prediction Confidence")

    st.write("Stay")
    st.progress(float(stay))
    st.write(f"{stay*100:.2f}%")

    st.write("Leave")
    st.progress(float(leave))
    st.write(f"{leave*100:.2f}%")

st.divider()