# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VDlliqYHU81TcG_NH-jNIu0RFmVUQpW2
"""

import streamlit as st
import pandas as pd
import plotly.express as px
import plotly.graph_objects as go
from sklearn.cluster import KMeans
from sklearn.datasets import load_iris

# ---------------------------------------------------
# Page Configuration
# ---------------------------------------------------
st.set_page_config(
    page_title="K-Means Clustering",
    page_icon="🌸",
    layout="wide"
)

# ---------------------------------------------------
# Sidebar
# ---------------------------------------------------
st.sidebar.title("🌸 K-Means Clustering")

st.sidebar.markdown("""
### About

This application demonstrates **K-Means Clustering**
using the famous **Iris Dataset**.

**Algorithm:** K-Means

**Dataset:** Iris Dataset
""")

st.sidebar.divider()

k = st.sidebar.slider(
    "Select Number of Clusters (K)",
    2,
    8,
    3
)

# ---------------------------------------------------
# Title
# ---------------------------------------------------
st.title("🌸 K-Means Clustering using Iris Dataset")

st.write("""
Cluster the Iris flower dataset using the **K-Means Algorithm**
and visualize the clusters along with their centroids.
""")

st.divider()

# ---------------------------------------------------
# Load Dataset
# ---------------------------------------------------
iris = load_iris()

df = pd.DataFrame(
    iris.data,
    columns=iris.feature_names
)

# ---------------------------------------------------
# Dataset Preview
# ---------------------------------------------------
st.header("📂 Dataset")

with st.expander("Click to View Dataset"):

    st.dataframe(df, use_container_width=True)

# ---------------------------------------------------
# Dataset Metrics
# ---------------------------------------------------
col1, col2, col3 = st.columns(3)

col1.metric(
    "🌼 Samples",
    df.shape[0]
)

col2.metric(
    "📊 Features",
    df.shape[1]
)

col3.metric(
    "🎯 Clusters",
    k
)

st.divider()

# ---------------------------------------------------
# Feature Selection
# ---------------------------------------------------
X = df[
    [
        "petal length (cm)",
        "petal width (cm)"
    ]
]

# ---------------------------------------------------
# Model Training
# ---------------------------------------------------
model = KMeans(
    n_clusters=k,
    random_state=42,
    n_init=10
)

df["Cluster"] = model.fit_predict(X)

# ---------------------------------------------------
# Clustered Dataset
# ---------------------------------------------------
st.header("📊 Clustered Dataset")

with st.expander("View Clustered Dataset"):

    st.dataframe(df, use_container_width=True)

st.divider()

# ---------------------------------------------------
# Charts
# ---------------------------------------------------
col1, col2 = st.columns(2)

with col1:

    fig = px.scatter(
        df,
        x="petal length (cm)",
        y="petal width (cm)",
        color=df["Cluster"].astype(str),
        title="Cluster Visualization"
    )

    fig.add_trace(
        go.Scatter(
            x=model.cluster_centers_[:,0],
            y=model.cluster_centers_[:,1],
            mode="markers",
            marker=dict(
                size=18,
                color="black",
                symbol="star"
            ),
            name="Centroids"
        )
    )

    st.plotly_chart(
        fig,
        use_container_width=True
    )

with col2:

    sse=[]

    for i in range(1,10):

        km = KMeans(
            n_clusters=i,
            random_state=42,
            n_init=10
        )

        km.fit(X)

        sse.append(km.inertia_)

    elbow_df = pd.DataFrame({
        "Clusters":range(1,10),
        "SSE":sse
    })

    fig2 = px.line(
        elbow_df,
        x="Clusters",
        y="SSE",
        markers=True,
        title="Elbow Method"
    )

    st.plotly_chart(
        fig2,
        use_container_width=True
    )

st.divider()

# ---------------------------------------------------
# Cluster Centers
# ---------------------------------------------------
st.header("🎯 Cluster Centers")

centers = pd.DataFrame(
    model.cluster_centers_,
    columns=[
        "Petal Length (cm)",
        "Petal Width (cm)"
    ]
)

with st.expander("View Cluster Centers"):

    st.dataframe(
        centers,
        use_container_width=True
    )

st.divider()

# ---------------------------------------------------
# Observations
# ---------------------------------------------------
with st.expander("📌 Observations"):

    st.markdown(f"""
- The algorithm divided the flowers into **{k} clusters**.

- Each cluster represents flowers with similar petal measurements.

- The **black stars** in the scatter plot represent the **cluster centroids**.

- The Elbow Method helps determine the optimal value of **K**.
""")

st.success(
    f"✅ K-Means Clustering successfully created **{k} clusters**."
)

st.divider()